### ISSUE TITLE
Where does input data/5flm.pdb come from?

### ISSUE THREAD

**Issue by benmwebb** [integrativemodeling/pol_ii_g#1]
@saijananiganesan where does input `data/5flm.pdb` come from? It looks like a subset of the 'real' PDB 5flm, maybe rotated and translated for some reason? If so, you should add a header to the file to describe how this transformation was done. See https://python-ihm.readthedocs.io/en/latest/metadata.html#ihm.metadata.PDBParser.parse_file

**Comment by saijananiganesan** [comment]
@benmwebb I got the file from experimentalists. I will find out.

**Comment by benmwebb** [comment]
Thanks!
