### ISSUE TITLE
What are the models in the `results/models` directory?

### ISSUE THREAD

**Issue by benmwebb** [integrativemodeling/pol_ii_g#2]
@saijananiganesan I see exactly 100 models in the `results/models` directory. What are these? (There is a readme file but it is empty!)

 - What does the naming scheme mean? They are named `X_Y.rmf3` - what is the significance of the two numbers `X` and `Y`?
 - Do these models correspond to the localization densities? (If not, we'll need the set of models that do.)
 - What are these models? All models in the largest cluster? Top 100 models in that cluster? From the paper I see various clustering was done but I don't see the number "100" mentioned anywhere and it seems like a suspiciously round number for a cluster size. I see you also have a clustering subdirectory but the format of the files in there isn't explained in the (empty) readme.

**Comment by saijananiganesan** [comment]
@benmwebb , there has been an uploading error. There is supposed to be 1693 models in the folder. I will zip it and upload it today. These are good scoring models, and only a part of it is used for clustering. 
X refers to run number and Y is the frame number. [As you can see only frames 1-7 runs have been uploaded)]. I have defined this format in the main readme file. I will update all the readme files. 
I will also zip the models in the cluster. Thanks for checking Ben!

**Comment by benmwebb** [comment]
Great, thanks.

**Comment by benmwebb** [comment]
Looks good - so the only remaining point: which set of models do the localization densities correspond to? All 1693 models, or a subset? (If a subset, which subset?)

**Comment by saijananiganesan** [comment]
It corresponds to models from the cluster. I will add it to the readme files.
